[package]
name = "datafusion-mongo-connector"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = { version = "1.2", default-features = false, features = ["sync"] }
datafusion = { git = "https://github.com/apache/arrow-datafusion" }
arrow = "4"
mongodb-arrow-connector = { version = "0.3", path = "../mongodb-arrow-connector" }
async-trait = "0.1"
futures = "0.3"
rayon = "*"
tokio = { version = "1.0", features = ["macros", "rt", "rt-multi-thread", "sync"] }
tokio-stream = "0.1"

[[bin]]
name = "load_data"
path = "bin/load_data.rs"