[package]
name = "datafusion-mongo-connector"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = { version = "1.2", default-features = false, features = ["sync"] }
datafusion = "4.0"
arrow = "4"
mongodb-arrow-connector = { version = "0.3" }
async-trait = "0.1"
futures = "0.3"